### ISSUE TITLE
Feature Request: Pass boolean to the storyFn when being run by puppeteer

### ISSUE THREAD

**Issue by nickradford** [reg-viz/storycap#105]
> Disclaimer: Love this project, combined with `reg-suit`, it's amazing.

It would be very nice if during the execution of `storybook-chrome-screenshot`, the `withScreenshot` decorator would pass a boolean to the story, which can be used to determine properties to pass to your components. An example would be if I were using the material UI tooltip in some of my UI, and I wanted it to be open in the screenshot pass, but not when I normally use storybook.

```jsx
storiesOf('SomeComponent', module)
  .add('this one is showing tooltips open', withScreenshot()(props =>(
    <Tooltip open={props.isScreenshot} title="Can't do that now">
      <Button>Disabled</Button>
    </Tooltip>
  ))
```

**Comment by Quramy** [comment]
I add the function `isScreenshot` to get whether the current process is in the screenshot browser:

```jsx
import { isScreenshot } from 'storycap';

storiesOf('SomeComponent', module)
  .add('this one is showing tooltips open', withScreenshot()(props =>(
    <Tooltip open={isScreenshot()} title="Can't do that now">
      <Button>Disabled</Button>
    </Tooltip>
  ))
```
