### ISSUE TITLE
Check for config.ts as well as config.js

### ISSUE THREAD

**Issue by roalonso** [reg-viz/storycap#106]
Storybook supports using a .ts file extension for the config file (see https://github.com/storybooks/storybook/pull/3913).
However, when using an extension other than `.js`, storybook-chrome-screenshot throws
```
ERROR  ".storybook/config.js" does not exists.
```
It still continues and generates the screenshots correctly. This check should be either removed or updated to check for .ts as well.

**Comment by Quramy** [comment]
Hi. We've released the new version of this project(formally *Storycap*). We separates booting Storybook process from main screenshot procedure. In the new version, we design users own the responsibility to boot Storybook correctly.

For example:

```sh
$ npm run start-storybook -p 9009 &
$ npx storycap http://localhost:9009
```

You can call with one-liner via `--serverCmd` option:

```sh
$ npx storycap --serverCmd "start-storybook -p 9009" http://localhost:9009
```
