### ISSUE TITLE
storybook-chrome-screenshot freezes when Storybook component fails to render

### ISSUE THREAD

**Issue by roalonso** [reg-viz/storycap#108]
When this happens a better handling would be to end storybook-chrome-screenshot with an error.

This is what is shown on Storybook:
<img width="1438" alt="screen shot 2019-03-04 at 3 53 57 pm" src="https://user-images.githubusercontent.com/6528419/53771033-fdc36100-3e95-11e9-8df7-43baebb681f4.png">

When something goes wrong while trying to render the story, the body is given the class `sb-show-errordisplay`.

**Comment by Quramy** [comment]
Hi. We've released the new version of this project (formally *Storycap*). Storycap has function to detect timeout while capturing procedure. Please check it out ! 😄
