### ISSUE TITLE
Fix compatibility with Storybook 5

### ISSUE THREAD

**Issue by sisisin** [reg-viz/storycap#114]
Storybook v5 has changed `setStories` API, this causes to break `Client#searchTargetStories` ( [this line](https://github.com/tsuyoshiwada/storybook-chrome-screenshot/blob/master/src/core/client/Client.ts#L76) )
At Storybook v5, `setStories` event's callback receive not `Array`, but `Object`.

ref. https://github.com/Quramy/zisui/issues/6

**Comment by w4-hojin** [comment]
https://github.com/storybooks/storybook/blob/cfacc56856f13465bce2e0dd2434384d7334e40b/lib/api/src/index.tsx#L143
https://github.com/storybooks/storybook/blob/cfacc56856f13465bce2e0dd2434384d7334e40b/lib/api/src/modules/stories.ts#L71

**Comment by Quramy** [comment]
Hi. We've released the next version of this project, formally Storycap (And Storycap's was based zisui sources). Storycap supports Storybook v5.2. Please check it out!
