### ISSUE TITLE
v2 publish in es5?

### ISSUE THREAD

**Issue by ysgk** [reg-viz/storycap#131]
Hi, thank you for this library. We are currently looking into storycap for our product.

Storycap v2 is currently published in esnext, but our product supports IE11. We need compile storycap, a 3rd party library in node_modules, using babel to make storybook run on IE. Updating babel config just for capturing stories seems to me a bit of an extra work. I would appreciate if you could publish storycap in es5. Any reason for publishing storycap in esnext although storybook itself is es5?

**Comment by Quramy** [comment]
Oh, thanks. I’ll consider it!

**Comment by Quramy** [comment]
Hi @ysgk . I've modified the transpiling target to `ES5` and published it as v2.1.0. Please check it out 😄

**Comment by ysgk** [comment]
@quramy
Now babel is no longer needed 👍  IE is still throwing an error, because `new URL` is used [here](https://github.com/reg-viz/storycap/blob/master/packages/storycap/src/client/trigger-screenshot.ts#L29), though. I added `url-polyfill` and it's working fine now. Any way, thank you for your quick response!

**Comment by Quramy** [comment]
Thanks for your feedback!
