### ISSUE TITLE
Include puppeteer as peerDependencies 

### ISSUE THREAD

**Issue by dora1998** [reg-viz/storycap#235]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently storycap includes puppeteer as one of dependencies.
https://github.com/reg-viz/storycap/blob/master/packages/storycap/package.json#L69

However, puppeteer will download chromium app as default on install. It makes node_modules bigger and installation time longer, though we mainly capture screenshots only on CI.

## Describe the solution you'd like

Storycap marks puppeteer as one of peerDependencies, then we can install storycap by the following command.

```
$ yarn install storycap puppeteer
```

## Describe alternatives you've considered

- Create package only includes setting decorator for Storybook
- Users who don't want to install chromium set `puppeteer_skip_chromium_download` true in `.npmrc`

## Additional context

In some of my projects, reg-suit and relevant packages are installed by separated package.json from application's one. Therefore, I don't want to install large packages in application's package.json for CI test, so I created this issue.

**Comment by Quramy** [comment]
Thanks for reporting, I'll consider it

**Comment by Quramy** [comment]
@dora1998 
I've released Storycap v3 and it uses puppeteer-core instead of puppeteer.

**Comment by dora1998** [comment]
@Quramy 
Thank you so much for your extremely quick implement!
