### ISSUE TITLE
Store snapshots next to source file folders

### ISSUE THREAD

**Issue by raDiesle** [reg-viz/storycap#284]
It would be awesome to support a way - if not you may give guidance, how to achieve so that images are stored next to the location of the defined .stories. file definitions. We do believe it is more handy to have the test result next to the test.

**Comment by Quramy** [comment]
Storycap is responsible for only capturing Storybook stories and does not provide function to compare images nor snapshot testing because we intend "separation of concern".

You can comparison or updating snapshots with reg-cli command:

```sh
$ npx storycap snapshots http://localhost:6006       # Capture stories
$ npx reg-cli __screenshots__ __snapshots__ diff -R  # compare
```

If reg-cli fail, 

```sh
$ npx reg-cli __screenshots__ __snapshots__ diff -U # Update snapshot images
$ git add __snapshots__
``` 

If you want more details, see https://github.com/reg-viz/reg-cli#cli .

**Comment by raDiesle** [comment]
The request was about idea to store the screenshots not in the folder structure of the story kind and storyName, but filestructure location of stories definition.

(Indeed this would require for the proper workflow as well reg-cli to support it.)

**Comment by andre-brdoch** [comment]
We would find that very useful as well. It would allow users to have a folder structure like this one:
```
| Button
  |-- Button.vue
  |-- Button.stories.js
  |-- tests
     |-- screenshots
```

The screenshots of a particalur component could be inspected when working on that component, without having to search through a folder with hundreds of screenshots of all stories.
