### ISSUE TITLE
Support waitFor in managed mode

### ISSUE THREAD

**Issue by raDiesle** [reg-viz/storycap#293]
I would find waitFor support for "simple"- mode useful:

when a by convention variable exist on a story, apply waitFor on it I could use "simple" mode, instead of "managed".

I dont see its a customized setting required, just an option to tell the page when its ready to take a screenshot.

Another solution to the same problem would be to introduce --waitFor argument to the simple mode.

e.g. 

stories( ... () => 
window.storycap_waitForIsResolved = Promise.resolve(false);

clickMyButtonWithWebdriverCallback = () => {
     window.storycap_waitForIsResolved = Promise.resolve(true);
}
return <jsx>;

**Comment by Quramy** [comment]
Do you intend "Support waitFor in simple mode" ?

I think you should use managed mode if you want to control how story is captured using complex condition.

**Comment by raDiesle** [comment]
I dont see a disadvantage to have the conditions in the stories itself. so my waitFor condition is always the same "wait for THE flag to become true.

**Comment by Quramy** [comment]
> so my waitFor condition is always the same "wait for THE flag to become true

I think you can achieve this by setting managed mode and the condition as global parameter. 

```js
/* .storybook/config.js */

addParameters({
  screenshot: {
    waitFor: yourGlobalConditionFn(),    
  },
});
```

Is there problem with this method? I don't see the necessity to add options to simple mode.

**Comment by raDiesle** [comment]
I agree.
I misunderstood there is simple and managed mode, which are expected to run combined, not eigher or.

In this case there is no issue to attach managed mode to simple mode and still let it run by npx storycap command.

Thanks!
