### ISSUE TITLE
Setting $(npm bin) on Windows

### ISSUE THREAD

**Issue by ValeryIvanov** [reg-viz/storycap#31]
I get this error on my Windows development machine.

```
  cmd: 'C:\\frontend\\$(npm bin)\\start-storybook' }

 ERROR  Storybook does not exists. First, let's setup a Storybook!
        See: https://storybook.js.org/basics/quick-start-guide/

 LAUNCH  Launching storybook server ...

 DEBUG  [Command Arguments] -p 6006 -c .storybook -h localhost
error Command failed with exit code 1.
```

Seems that this is environment specific issue, here is similar problem
https://github.com/Semantic-Org/Semantic-UI-React/issues/315

Recommendation is to use something like this
https://github.com/kentcdodds/cross-env

**Comment by tsuyoshiwada** [comment]
Hi @ValeryIvanov, Thank for report !!  Also, I'm very sorry that the reply was delayed ... :sob:

Currently, I do not have a windows terminal at hand.
But there are plans to get it soon :muscle:

I will consider formally addressing the correspondence at that time.
Thanks :pray:

**Comment by ValeryIvanov** [comment]
Hi! Any progress with that issue? Do you need help with that?

**Comment by radix** [comment]
As a hint, @tsuyoshiwada, you can replace `execSync('echo $(npm bin)', ...)` with just `execSync('npm bin', ...)` in your `execSync` call.

But there's another minor incompatibility, in the invocation of `start-storybook` -- it needs to invoke `start-storybook.cmd` on Windows (the `.cmd` extension isn't automatically added unlike stuff like `.exe` and `.bat`). I'm sure there's some library on npm that takes care of cross-platform command execution which can help with this, but I haven't looked yet.

**Comment by adirn15** [comment]
Hi @tsuyoshiwada, did you manage to resolve the issue?
I'm currently experiencing the same problem on my windows dev machine

Thanks

**Comment by Quramy** [comment]
Hi. We released the next version of this project. The new version, formally *Storycap*, only needs URL of Storybook server you boot. Please check out https://github.com/reg-viz/storycap#getting-started
