### ISSUE TITLE
Custom suffix for images instead of dimensions

### ISSUE THREAD

**Issue by divyanshshukla-shift** [reg-viz/storycap#372]
Hi!

Is there way to use a custom suffix for the image snapshots? 
For example, to use `Button_destop.png` instead of `Button_1920x1080.png` for all the 1920x1080 images.

**Comment by Quramy** [comment]
Hi @divyanshshukla-shift .

If you use Storycap with simple-mode ( https://github.com/reg-viz/storycap#getting-started ), you can't change the suffix.

Otherwise, if you use Storycap with managed mode ( https://github.com/reg-viz/storycap#managed-mode ), pls try the following configuration:

```js
/* .storybook/preview.js */

import { withScreenshot } from 'storycap';

export const decorators = [
  withScreenshot, // Registration the decorator is required
];

export const parameters = {
  screenshot: {
    // each key of viewport is used as filename suffix
    viewports: {
      large: {
        width: 1024,
        height: 768,
      },
      small: {
        width: 375,
        height: 668,
      },
      xsmall: {
        width: 320,
        height: 568,
      },
    },
  },
};
```

**Comment by divyanshshukla-shift** [comment]
Thanks for the response.
Does the managed mode work with the static build of storybook?

**Comment by divyanshshukla-shift** [comment]
It does work indeed! However, we also need to add storycap to `.storybook/main.js` as stated in the docs.

Thanks for the help.
