### ISSUE TITLE
warn Capture timeout exceeded in 5000 msec on managed mode only

### ISSUE THREAD

**Issue by alexbae-nyt** [reg-viz/storycap#460]
Only seeing this error on managed mode. When running storycap in simple mode it works without errors

**Comment by toughdeveloper** [comment]
Hey @alexbae-nyt. Were you able to resolve this? I'm seeing the same issue.

**Comment by alexbae-nyt** [comment]
@toughdeveloper It was an issue with the version of Chrome I was using. I am using Chrome version 95 and it is working now
