### ISSUE TITLE
Sometimes browser process does not resolve capture image

### ISSUE THREAD

**Issue by Quramy** [reg-viz/storycap#545]
Since version v3.1.1 

Sometimes browser process does not resolve capture image.  We should investigate which promise is pending.

**Comment by Quramy** [comment]
It may be depends on puppeteer-core version.

**Comment by Quramy** [comment]
I don't know reproducing condition 🤔 

- Storycaps repository's CI works well
- With Stroybook(it's in private repos in my work)
  - Storycap works well /w my local mac
  - **But It hangs up in CI jobs** 

Some CI logs seems to indicate that `resourceWatcher

**Comment by yshrsmz** [comment]
Hi, I think my project(at work) can reproduce this locally.
I cannot share the code, but please let me know if I can help you.

**Comment by yshrsmz** [comment]
This error hits me again with storycap v4.0.0 and puppeteer v19.7.5.
Can reproduce locally, and might be related to #563 as well.
