### ISSUE TITLE
Await exposeFunction in CapturingBrowser

### ISSUE THREAD

**Issue by Jamie5** [reg-viz/storycap#631]
In https://github.com/reg-viz/storycap/blob/master/packages/storycap/src/node/capturing-browser.ts we currently call `exposeFunction` without awaiting the result. It seems better to await it for several reasons

1. The puppeteer documentation shows awaiting of the method in e.g. https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.page.exposefunction.md
2. The answer here: https://stackoverflow.com/questions/64922568/error-evaluation-failed-invalid-arguments-should-be-exactly-one-string-pup suggests that not awaiting can lead to an error which looks similar to something I ran into
3. When adding an await, it seems like issues I had running storycap manually just went away

**Comment by Mike-Dax** [comment]
I've hit this error as well, I've made a PR.
