### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by joevaugh4n** [reg-viz/storycap#838]
Hey @Quramy! I’m reaching out from the Storybook core team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

We also have an addons channel in our Discord community, which we’d like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message me (@joevaugh4n) so that I can give you the addon creator role! If you’re already in the server, please just ping me and I’ll respond to you there.

Thanks for being a part of our addon community!

Joe

**Comment by hrigner** [comment]
Any progress here? :)

**Comment by indigolain** [comment]
I have just added changes to support Storybook version 8 with https://github.com/reg-viz/storycap/pull/855 ✨ 
It has not been released yet, but may be available soon.

**Comment by indigolain** [comment]
Looks like v4.3.0 including Storybook version 8 support is released 🎉
https://github.com/reg-viz/storycap/releases/tag/v4.3.0
