### ISSUE TITLE
Has `withScreenshot` been deprecated?

### ISSUE THREAD

**Issue by k35o** [reg-viz/storycap#869]
The interface in `withScreenshot` was marked `@deprecated`.
https://github.com/reg-viz/storycap/blob/masater/packages/storycap/src/client/with-screenshot.ts#L14-L19

However, the [v8 example](https://github.com/reg-viz/storycap/blob/master/examples/v8-react18/.storybook/preview.js) used `withScreenshot` until.

What is the status of `withScreenshot` now?
If `withScreenshot` has been deprecated, I need an example of not using it!

**Comment by Quramy** [comment]
The `withScreenshot` decorator itself is NOT deprecated. 

But,  higher order function  usage of this like `withScreenshot({ viewport: ,,, })` is deprecated.

**Comment by k35o** [comment]
Thanks!
