### ISSUE TITLE
Fix compatibility with Storybook 4

### ISSUE THREAD

**Issue by janpaul123** [reg-viz/storycap#92]
Seems to be broken without any error message, which is quite confusing. See even this automatically generated PR: https://github.com/tsuyoshiwada/storybook-chrome-screenshot/pull/91

> Fetching the target components ...
>
> Too long with no output (exceeded 10m0s)

**Comment by LucianBuzzo** [comment]
@tsuyoshiwada Can this issue be closed?

**Comment by shanez** [comment]
@LucianBuzzo  There are still compatibility issues.  Upgrading to storybook 4 causes the viewport to not be set correctly in puppeteer.
