### ISSUE TITLE
SCS v2

### ISSUE THREAD

**Issue by tsuyoshiwada** [reg-viz/storycap#95]
## Overview

We are planning to release v2 for the purpose of improving performance, function, and much more :muscle:
At the same time we aim to change the code base to maintainable.

## Philosophy
**Performance and stability** are most important characteristics. SCS was designed in order to VRT(Visual Regression Testing) using Storybook. In other words, SCS runs on not users' local machine but CI environments. So SCS must complete capture tasks in realistic execution time and must not hangup in CI jobs.

## Basic implementation plan
We'll integrate [zisui](https://github.com/Quramy/zisui) to SCS. *zisui* is a tool very similar to SCS. It crawls Storybook and capture screenshot for each story using Puppeteer.

## Features comparison

| Feature                                           | SCS v1              | zisui               | SCS v2          | Priority |
| :-------------------------                        | :----:              | :----:              | :----:          | :------: |
| Storybook v4 compatibility                        | :white_check_mark:  | :white_check_mark:  | :+1:            | BETTER   |
| Storybook v5 compatibility                        |                     | :white_check_mark:  | :+1:            | MUST     |
| Decorator for React                               | :white_check_mark:  | :white_check_mark:  | :+1:            | MUST     |
| Decorator for Angular                             | :white_check_mark:  |                     | :+1:            | MUST     |
| Decorator for Vue                                 | :white_check_mark:  |                     | :+1:            | MUST     |
| `addParameters` signature support                 |                     |                     | :+1:            | BETTER   |
| Parallel Puppeteer bootstrapping                  | :white_check_mark:  | :white_check_mark:  | :+1:            | MUST     |
| Puppeteer launch configuration                    | :white_check_mark:  |                     | :+1:            | MUST     |
| Serve Storybook within CLI                        | :white_check_mark:  | :white_check_mark:  | :+1:            | MUST     |
| Use built or served Storybook                     |                     | :white_check_mark:  | :+1:            | MUST     |
| Zero configuration (Simple mode)                  |                     | :white_check_mark:  | :+1:            | MUST     |
| Filter story name to capture                      | :white_check_mark:  | :white_check_mark:  | :+1:            | MUST     |
| Timeout handling to connect Storybook server      | :white_check_mark:  | :white_check_mark:  | :+1:            | MUST     |
| Timeout handling to capture each story            |                     | :white_check_mark:  | :+1:            | MUST     |
| Automatic disable CSS animation                   |                     | :white_check_mark:  | :+1:            | MUST     |
| Exporting SCS specific environment info           |                     |                     | :neutral_face:  | BETTER   |
| Inject arbitrary JavaScript files to Chrome       | :white_check_mark:  |                     | :thinking:      | LOW      |
| Multiple viewports for each story                 | :white_check_mark:  |                     | :+1:            | MUST     |
| Full page support                                 |                     | :white_check_mark:  | :+1:            | MUST     |
| Namespace and overriding default namespace        | :white_check_mark:  |                     | :thinking:      | LOW      |
| Force override element's state (e.g. `:focus`     |                     |                     | :+1:            | BETTER   |
| addon-knobs support                               | :white_check_mark:  |                     | :no_entry_sign: | LOW      |
| Wait for capture till `<img>` in the story loaded | :white_check_mark:  | :white_check_mark:  | :+1:            | MUST     |
| Wait for capture during provided times elapsed    | :white_check_mark:  | :white_check_mark:  | :+1:            | MUST     |
| Wait for capture till user specified func called  | :white_check_mark:  | :white_check_mark:  | :+1:            | MUST     |
| Wait for capture till browser metrics stabled     |                     | :white_check_mark:  | :+1:            | MUST     |

#### Example

```jsx
storiesOf('Button', module)
  .addParameters({
    screenshot: {
      focus: 'button', // It should be a valid CSS selecotr in this story
      // or
      // hover: 'a[data-button-link-target]',
    },
  })
  .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
```

#### How to implement
We can use Puppeteer API (see https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagefocusselector) .

### Additional parameters
The following features require function to generate from a single story definition to multiple screenshot captures.

- Namespace and overriding default namespace
- Multiple viewports
- Force override element's state

We introduce `variants` section to do them. `variants` tells the additional configuration to SCS and defines suffix of the PNG file name corresponding.

```ts
type ScreenshotOptions = {
  delay?: number;
  viewport?: Viewport;
  // ... other options
  variants?: {
    [key: string]: ScreenshotOptions;
  };
};
```

#### Example 1

```jsx
/* .storybook/config.js */
addParameters({
  screenshot: {
    viewport: {
      width: 1200,
      height: 800,
    },
  },
});

/* components/button.stories.jsx */

storiesOf('Button', module)
  .addParameters({
    screenshot: {
      variants: {
        focused: { // the key is used for suffix of the PNG file name
          focus: 'button',
        },
      },
    },
  })
  .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
```

The above code generates:

- `Button/with text.png` (derived from the default)
- `Button/with text_focused.png` (derived from the `focused` variant)

#### Example 2
Next, more complex example:

If there is the following global configuration:

```js
/* .storybook/config.js */
addParameters({
  screenshot: {
    viewport: {
      width: 1200,
      height: 800,
    },
    variants: {
      sp: { viewport: 'iPhone6' },
      sp_xs: { viewport: 'iPhone5SE' },
    },
  },
});
```

This generates 3 PNGs for each story.

And more configuration can be added by the story file:

```jsx
/* components/button.stories.jsx */

storiesOf('Button', module)
  .addParameters({
    screenshot: {
      variants: {
        focused: {
          focus: 'button',
          followWith: ['sp'], // It indicates to add this config to both the default and "sp" configuration. 
        },
      },
    },
  })
  .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
```

Finally the above story code generates:

- `Button/with text.png` (derived from the default)
- `Button/with text_sp.png` (derived from the global `sp` variant)
- `Button/with text_sp_xs.png` (derived from the global `sp_xs` variant)
- `Button/with text_focused.png` (derived from the story's `focused` variant)
- `Button/with text_sp_focused.png` (derived from the combination `sp` and `focused` variants, which `followWith` directive creates)

#### How to implement

We can't know the screenshot option when SCS visits each story for the first time. `withScreenshot` decorator **generates** 1 or more screenshot options, so if the first time emitted option has additional configurations we should generate tasks to capture for each additional conf ( I think JavaScript **generator** is suitable to do this ) .

---

_It's scheduled to be updated from time to time._

**Comment by Quramy** [comment]
We've released `storycap@2.0.0` 🎉
